spring.application.name=messaging
server.port=8081
spring.mail.host=smtp.gmail.com
spring.datasource.url=jdbc:postgresql://localhost:5432/messaging
spring.datasource.username=postgres
spring.datasource.password=emacutevs
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=@123456qQ
